SELECT 
    c.NAME AS COURSE_NAME,
    CONCAT(s.FIRST_NAME, ' ', s.LAST_NAME) AS STUDENT_NAME
FROM [Courses].[dbo].[COURSES] c
INNER JOIN [Courses].[dbo].[GROUPS] g ON c.COURSE_ID = g.COURSE_ID
INNER JOIN [Courses].[dbo].[STUDENTS] s ON g.GROUP_ID = s.GROUP_ID
ORDER BY c.NAME, s.FIRST_NAME, s.LAST_NAME;
